"""
Django settings for FutFemGames project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, mimetypes
mimetypes.add_type("application/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carpeta donde Django buscará archivos subidos
MEDIA_ROOT = BASE_DIR / 'futfem' / 'media'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# 2. Donde Compressor guardará sus archivos generados (normalmente lo mismo que STATIC_ROOT)
COMPRESS_ROOT = STATIC_ROOT

# URL pública para acceder a esos archivos
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
COMPRESS_URL = STATIC_URL # Esto le dice al compresor que use la misma ruta
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# Cache de larga duración (1 año) para archivos que no cambian
WHITENOISE_MAX_AGE = 31536000 
WHITENOISE_IMMUTABLE_FILE_SUPPORT = True
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False # Evita errores si falta algún archivo
WHITENOISE_ROOT = os.path.join(BASE_DIR, 'media')

# Esto asegura que si cambias el archivo, Django le cambie el nombre (hash)
# para que el navegador descargue la versión nueva.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tylyd1o(l$na1k@hd!vw!6e767zw$$v5b_02p$$wbuv+f9wk7p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

DEBUG_TOOLBAR_CONFIG = {
    'INTERCEPT_REDIRECTS': False,
    'SHOW_TOOLBAR_CALLBACK': lambda request: True, # Fuerza a que se muestre siempre en DEBUG
    'RESULTS_CACHE_SIZE': 100,  # Aumenta el historial de resultados
    'RENDER_PANELS': True,
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django_browser_reload',
    "debug_toolbar",
    'compressor',
    'minijuegos',
    'futfem',
    'FutFemWiki',
    'usuarios'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'FutFemGames.middleware.CustomWhiteNoiseMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',       # <--- SUBE AQUÍ
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder', # <--- Obligatorio
)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

COMPRESS_ENABLED = True
COMPRESS_OFFLINE = False 

ROOT_URLCONF = 'FutFemGames.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.usuario_sesion',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

CSRF_TRUSTED_ORIGINS = [
    'https://futfemgames.gti-ia.upv.es',
    'https://*.trycloudflare.com',
    'http://*.trycloudflare.com',
    'https://127.0.0.1:8000',
]

WSGI_APPLICATION = 'FutFemGames.wsgi.application'

# settings.py
AUTH_USER_MODEL = 'usuarios.Usuario'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQLDATABASE', 'futfemgames'), # Railway usa MYSQLDATABASE
        'USER': os.getenv('MYSQLUSER', 'root'),           # Railway usa MYSQLUSER
        'PASSWORD': os.getenv('MYSQLPASSWORD', ''),       # Railway usa MYSQLPASSWORD
        'HOST': os.getenv('MYSQLHOST', '127.0.0.1'),       # Railway usa MYSQLHOST
        'PORT': os.getenv('MYSQLPORT', '3306'),           # Railway usa MYSQLPORT
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('ca', 'Valencià'), # Usamos 'ca' o 'ca-es-valencia' según tu preferencia
    ('en', 'English'),
    ('sv', 'Svenska'),
    ('nl', 'Nederlands'),
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / 'locale']
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # O smtp.gmail.com
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'valenciansports@gmail.com'
EMAIL_HOST_PASSWORD = 'wgobxjonfilvupwp'
