# Generated by Django 5.2.8 on 2026-05-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('escudo', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoFormacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temporada', models.CharField(db_column='temporada', max_length=10)),
                ('es_principal', models.BooleanField(db_column='es_principal', default=False)),
            ],
            options={
                'db_table': 'equipo-formacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoTrofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(db_column='temporada', max_length=10)),
            ],
            options={
                'verbose_name': 'Logro de Equipo',
                'verbose_name_plural': 'Palmarés',
                'db_table': 'equipo-trofeo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'formaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'juegos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id_jugadora', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('Apellidos', models.TextField()),
                ('Apodo', models.TextField()),
                ('Nacimiento', models.DateField(max_length=255)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('pie_habil', models.TextField(blank=True, max_length=12, null=True)),
                ('soccerdonna_url', models.URLField(blank=True, null=True, unique=True)),
                ('market_value', models.IntegerField(blank=True, null=True)),
                ('retiro', models.IntegerField(blank=True, null=True)),
                ('soccerdonna_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jugadoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JugadoraPais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_primaria', models.BooleanField(db_column='es_primaria', default=True)),
            ],
            options={
                'db_table': 'jugadora-pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id_liga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ligas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('iso', models.CharField(blank=True, db_column='iso', max_length=10, null=True)),
            ],
            options={
                'db_table': 'paises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor', models.TextField()),
            ],
            options={
                'db_table': 'pistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('idPosicion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('abreviatura', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'posiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trayectoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('años', models.TextField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('equipo_actual', models.BooleanField()),
            ],
            options={
                'db_table': 'trayectoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipo', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trofeos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JugadoraPosicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_primaria', models.BooleanField(db_column='es_primaria', default=True)),
                ('jugadora', models.ForeignKey(db_column='jugadora', on_delete=django.db.models.deletion.CASCADE, to='futfem.jugadora')),
                ('posicion', models.ForeignKey(db_column='posicion', on_delete=django.db.models.deletion.CASCADE, to='futfem.posicion')),
            ],
            options={
                'db_table': 'jugadora-posicion',
                'managed': False,
            },
        ),
    ]
